-- Export des JokerTemplate pour installation du projet
-- Généré le 2026-02-19 00:47:57

SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (51, 'Vampire', 'uncommun', 'Gagne x0.5 Mult par carte Enhanced jouée. Se réinitialise à la fin du round.', '/images/jokers/vampire.png', 'vampire', '{\"trigger\":\"on_card_played\",\"card_type\":\"enhanced\"}', 'xmult', 0.5);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (52, 'Baron', 'rare', 'Chaque Roi en main donne x1.5 Mult', '/images/jokers/baron.png', 'baron', '{\"trigger\":\"card_held\",\"card_rank\":\"King\"}', 'none', 0);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (53, 'Joker', 'commun', '+4 Mult', '/images/jokers/joker.png', 'simple_mult', '{\"trigger\":\"always\"}', 'mult_flat', 4);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (54, 'Greedy Joker', 'commun', 'Les cartes jouées avec la couleur Diamond donnent +3 Mult lorsqu\'elles sont scorées', '/images/jokers/greedy.png', 'greedy_joker', '{\"suit\":\"Diamond\",\"trigger\":\"on_card_scored\"}', 'mult_flat', 3);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (55, 'Lusty Joker', 'commun', 'Les cartes jouées avec la couleur Heart donnent +3 Mult lorsqu\'elles sont scorées', '/images/jokers/lusty.png', 'lusty_joker', '{\"suit\":\"Heart\",\"trigger\":\"on_card_scored\"}', 'mult_flat', 3);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (56, 'Wrathful Joker', 'commun', 'Les cartes jouées avec la couleur Spade donnent +3 Mult lorsqu\'elles sont scorées', '/images/jokers/wrathful.png', 'wrathful_joker', '{\"suit\":\"Spade\",\"trigger\":\"on_card_scored\"}', 'mult_flat', 3);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (57, 'Gluttonous Joker', 'commun', 'Les cartes jouées avec la couleur Club donnent +3 Mult lorsqu\'elles sont scorées', '/images/jokers/gluttonous.png', 'gluttonous_joker', '{\"suit\":\"Club\",\"trigger\":\"on_card_scored\"}', 'mult_flat', 3);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (58, 'Scary Face', 'commun', 'Les cartes Figures jouées donnent +30 Chips lorsqu\'elles sont scorées', '/images/jokers/scary_face.png', 'scary_face', '{\"trigger\":\"on_card_scored\",\"card_type\":\"face\"}', 'chips', 30);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (59, 'Abstract Joker', 'commun', '+3 Mult par Joker possédé', '/images/jokers/abstract.png', 'abstract_joker', '{\"trigger\":\"per_joker\"}', 'mult_flat', 3);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (60, 'Mystic Summit', 'commun', '+15 Mult si 0 défausses restantes', '/images/jokers/mystic_summit.png', 'mystic_summit', '{\"value\":0,\"trigger\":\"discards_remaining\"}', 'mult_flat', 15);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (61, 'Fibonacci', 'uncommun', 'Chaque As, 2, 3, 5 ou 8 joué donne +8 Mult lorsqu\'il est scoré', '/images/jokers/fibonacci.png', 'fibonacci', '{\"ranks\":[\"A\",\"2\",\"3\",\"5\",\"8\"],\"trigger\":\"on_card_scored\"}', 'mult_flat', 8);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (62, 'Loyalty Card', 'uncommun', 'x1.25 Mult tous les 6 mains jouées. Augmente de x0.25 tous les 6 mains.', '/images/jokers/loyalty_card.png', 'loyalty_card', '{\"trigger\":\"every_n_hands\",\"interval\":6}', 'xmult', 0.25);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (63, 'Constellation', 'uncommun', 'Gagne x0.1 Mult par carte Planet utilisée', '/images/jokers/constellation.png', 'constellation', '{\"trigger\":\"on_planet_card_used\"}', 'xmult', 0.1);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (64, 'Hiker', 'uncommun', 'Chaque main jouée donne définitivement +4 Chips', '/images/jokers/hiker.png', 'hiker', '{\"trigger\":\"on_hand_played\"}', 'chips', 4);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (65, 'Square Joker', 'commun', '+16 Chips si la main jouée contient exactement 4 cartes', '/images/jokers/square.png', 'square_joker', '{\"value\":4,\"trigger\":\"hand_size\"}', 'chips', 16);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (66, 'Raised Fist', 'commun', 'Ajoute le rang de la carte de rang le plus bas en main aux Mult (doublé si la carte a une amélioration)', '/images/jokers/raised_fist.png', 'raised_fist', '{\"trigger\":\"lowest_rank_in_hand\"}', 'mult_flat', 15);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (67, 'Chaos the Clown', 'commun', '1 reroll gratuit par shop', '/images/jokers/chaos.png', 'chaos_clown', '{\"trigger\":\"shop_reroll\"}', 'mult_flat', 0);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (68, 'Blue Joker', 'commun', '+2 Chips par carte restante dans le deck', '/images/jokers/blue.png', 'blue_joker', '{\"trigger\":\"per_card_in_deck\"}', 'chips', 2);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (69, 'Supernova', 'commun', 'Ajoute le nombre de fois que la main de poker a été jouée à Mult', '/images/jokers/supernova.png', 'supernova', '{\"trigger\":\"poker_hand_level\"}', 'mult_flat', 1);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (70, 'Ride the Bus', 'commun', '+1 Mult par main jouée consécutive sans cartes Figure. Se réinitialise si vous jouez une Figure.', '/images/jokers/ride_bus.png', 'ride_the_bus', '{\"trigger\":\"consecutive_no_face\"}', 'mult_flat', 1);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (71, 'Space Joker', 'uncommun', '1 chance sur 4 d\'améliorer le niveau de la main de poker jouée', '/images/jokers/space.png', 'space_joker', '{\"trigger\":\"random\",\"probability\":0.25}', 'mult_flat', 0);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (72, 'Egg', 'commun', 'Gagne 3$ de valeur de vente à la fin du round', '/images/jokers/egg.png', 'egg', '{\"trigger\":\"end_of_round\"}', 'mult_flat', 3);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (73, 'Bootstraps', 'uncommun', '+2 Mult par tranche de 5$ que vous possédez (maximum $50)', '/images/jokers/bootstraps.png', 'bootstraps', '{\"max\":50,\"trigger\":\"per_5_dollars\"}', 'mult_flat', 2);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (74, 'Stuntman', 'uncommun', '+250 Chips, -1 taille de main', '/images/jokers/stuntman.png', 'stuntman', '{\"trigger\":\"always\"}', 'chips', 250);
INSERT INTO joker_template (id, nom, rarete, description, image, effet_code, condition_activation, type_stack, stack_par_unite) VALUES (75, 'Runner', 'commun', '+15 Chips si la main contient une Straight', '/images/jokers/runner.png', 'runner', '{\"trigger\":\"poker_hand\",\"hand_type\":\"Straight\"}', 'chips', 15);

SET FOREIGN_KEY_CHECKS = 1;
